name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    # - name: Install cmake
    #   run: sudo apt-get install -y cmake make #install cmake to build
      
    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        
    - name: Configure CMake
      run: cmake -Bbuild -H -G "Visual Studio 17 2022" -A x64
      
    
      #change to run tests from a tests.cpp file instead
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make
